// Primitivas visuales de Atlas («Observatorio»). Importa desde "@/ui".
export { Button, IconButton } from "./Button";
export type { ButtonProps, ButtonVariant, ButtonSize, LinkButtonProps, IconButtonProps } from "./Button";
export { Card, InkCard, HeroNumber } from "./Card";
export type { CardProps, InkCardProps, HeroNumberProps } from "./Card";
export { Section, Page } from "./Section";
export type { SectionProps, PageProps } from "./Section";
export { SubjectTag, SubjectDot } from "./SubjectTag";
export type { SubjectTagProps, SubjectDotProps } from "./SubjectTag";
export { LevelBars, LEVEL_NAMES } from "./LevelBars";
export type { LevelBarsProps, LevelValue } from "./LevelBars";
export { Freshness, freshnessBand } from "./Freshness";
export type { FreshnessProps, FreshnessBand, FreshnessInfo } from "./Freshness";
export { Ring } from "./Ring";
export type { RingProps, RingTone } from "./Ring";
export { ProgressBar } from "./ProgressBar";
export type { ProgressBarProps, ProgressTone } from "./ProgressBar";
export { SegmentedBar } from "./SegmentedBar";
export type { SegmentedBarProps, BarSegment } from "./SegmentedBar";
export { Badge, RankGlyph } from "./Badge";
export type { BadgeProps, RankGlyphProps } from "./Badge";
export { Star, StarMark, StarDefs, STAR_STATE_LABELS } from "./Star";
export type { StarProps, StarMarkProps, StarState } from "./Star";
export { StarField } from "./StarField";
export type { StarFieldProps } from "./StarField";
export { Marker } from "./Marker";
export type { MarkerProps } from "./Marker";
export { Kbd } from "./Kbd";
export type { KbdProps } from "./Kbd";
export { Tabs, TabPanel, tabId, panelId } from "./Tabs";
export type { TabsProps, TabItem, TabPanelProps } from "./Tabs";
export { Segmented } from "./Segmented";
export type { SegmentedProps, SegmentedOption } from "./Segmented";
export { Tooltip } from "./Tooltip";
export type { TooltipProps } from "./Tooltip";
export { Dialog } from "./Dialog";
export type { DialogProps } from "./Dialog";
export { SidePanel } from "./SidePanel";
export type { SidePanelProps } from "./SidePanel";
export { Toaster, toast } from "./Toast";
export type { ToastOptions, ToastTone } from "./Toast";
export { EmptyState } from "./EmptyState";
export type { EmptyStateProps } from "./EmptyState";
export { Md, TeX, renderMarkdown } from "./Md";
export type { MdProps, TeXProps } from "./Md";
export { Heatmap } from "./Heatmap";
export type { HeatmapProps } from "./Heatmap";
export * from "./format";
export * from "./subjects";
export { cx, clamp, hashString, seededRandom } from "./cx";
export { useExitTransition, useReducedMotion, useRestoreFocus, useSvgId } from "./hooks";
export { Icons, ICON_SIZE, type IconName } from "./icons";
